plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

application {
    mainClass = 'quiz.Main'
}

javafx {
    version = '22'
    modules = ['javafx.controls', 'javafx.fxml', 'javafx.media']
}

run {
    jvmArgs = ['-Dprism.forceGPU=true']
}


dependencies {
    implementation 'com.jfoenix:jfoenix:9.0.10'
}